name: Sleep Workflow

on:
  push:
    branches:
      - main

jobs:
  sleep-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 2 seconds 1
        run: sleep 1.2
      - name: Sleep 2 seconds 2
        run: sleep 2.5
      - name: Sleep 2 seconds 2
        run: sleep 1.3
  sleep-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 2 seconds 12
        run: sleep 3.1
      - name: Sleep 2 seconds 22
        run: sleep 4.5
      - name: Sleep 2 seconds 22
        run: sleep 2.7